# Generated by Django 2.2.17 on 2021-02-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20210204_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.IntegerField(default=18),
        ),
    ]
