# Generated by Django 2.2.17 on 2021-02-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_category_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='test',
        ),
    ]
